package juego_gato;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import juego_gato.Jugador;
import juego_gato.Menu_Principal;
import juego_gato.Rifaa;

/**
 *
 * @author Hellen Lopez AAlejandro Salas
 */
public class Datos extends javax.swing.JFrame {
    /**
     * Creates new form Datos
     */
    Jugador jugador = new Jugador();
    public Datos() {
        initComponents();
        this.getContentPane().setBackground(Color.black);//Hace de color negro el fondo
        jugador.CargarCombo(cmbRegis1, cmbRegis2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJugador2 = new java.awt.TextField();
        jLbVS = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtJugador1 = new java.awt.TextField();
        btnSiguiente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        rboJ1Regis = new javax.swing.JRadioButton();
        rboJ1Nuevo = new javax.swing.JRadioButton();
        rboJ2Regis = new javax.swing.JRadioButton();
        rboJ2Nuevo = new javax.swing.JRadioButton();
        cmbRegis2 = new javax.swing.JComboBox();
        cmbRegis1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtJugador2.setBackground(new java.awt.Color(0, 0, 0));
        txtJugador2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtJugador2.setForeground(new java.awt.Color(255, 255, 255));
        txtJugador2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJugador2FocusLost(evt);
            }
        });
        getContentPane().add(txtJugador2);
        txtJugador2.setBounds(490, 250, 142, 28);

        jLbVS.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLbVS.setForeground(new java.awt.Color(255, 255, 255));
        jLbVS.setText("VS");
        getContentPane().add(jLbVS);
        jLbVS.setBounds(250, 70, 70, 58);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jugador 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 170, 79, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jugador 2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 170, 79, 22);

        txtJugador1.setBackground(new java.awt.Color(0, 0, 0));
        txtJugador1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtJugador1.setForeground(new java.awt.Color(255, 255, 255));
        txtJugador1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJugador1FocusLost(evt);
            }
        });
        getContentPane().add(txtJugador1);
        txtJugador1.setBounds(150, 250, 135, 28);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente);
        btnSiguiente.setBounds(170, 310, 90, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(410, 40, 98, 0);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 40, 98, 0);

        Cancelar.setText("Cancelar");
        Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarMouseClicked(evt);
            }
        });
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar);
        Cancelar.setBounds(380, 300, 90, 30);

        rboJ1Regis.setForeground(new java.awt.Color(255, 255, 255));
        rboJ1Regis.setSelected(true);
        rboJ1Regis.setText("Jugador Registrado");
        getContentPane().add(rboJ1Regis);
        rboJ1Regis.setBounds(20, 210, 120, 23);

        rboJ1Nuevo.setForeground(new java.awt.Color(255, 255, 255));
        rboJ1Nuevo.setText("Nuevo jugador");
        rboJ1Nuevo.setToolTipText("");
        getContentPane().add(rboJ1Nuevo);
        rboJ1Nuevo.setBounds(20, 250, 120, 23);

        rboJ2Regis.setForeground(new java.awt.Color(255, 255, 255));
        rboJ2Regis.setSelected(true);
        rboJ2Regis.setText("Jugador Registrado");
        getContentPane().add(rboJ2Regis);
        rboJ2Regis.setBounds(360, 210, 120, 23);

        rboJ2Nuevo.setForeground(new java.awt.Color(255, 255, 255));
        rboJ2Nuevo.setText("Nuevo jugador");
        rboJ2Nuevo.setToolTipText("");
        getContentPane().add(rboJ2Nuevo);
        rboJ2Nuevo.setBounds(360, 250, 120, 23);

        getContentPane().add(cmbRegis2);
        cmbRegis2.setBounds(490, 210, 140, 20);

        getContentPane().add(cmbRegis1);
        cmbRegis1.setBounds(150, 210, 130, 20);
        cmbRegis1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Jugador Jugador = new Jugador();
    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if(rboJ1Nuevo.isSelected()== true || rboJ1Regis.isSelected()== true){
            if (rboJ1Nuevo.isSelected()== true){
                if(txtJugador1.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null,"Debe de llenar correctamente los datos de jugador 1");
                }
            }
        }  
        if(rboJ2Nuevo.isSelected()== true || rboJ2Regis.isSelected()== true){
            if (rboJ2Nuevo.isSelected()== true){
                if(txtJugador2.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null,"Debe de llenar correctamente los datos de jugador 2");
                }
            }new Rifaa().setVisible(true);// hace el panel de rifa visible
            this.setVisible(false);
                }
         
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked

    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarMouseClicked

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        new Menu_Principal().setVisible(true);// hace el el menuprincipal visible
        this.setVisible(false);
    }//GEN-LAST:event_CancelarActionPerformed

    private void txtJugador1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJugador1FocusLost
       if(txtJugador1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debe de llenar correctamente los datos de jugador 1");
       }else{          
            if(Jugador.BuscarNombre(txtJugador1.getText())>0){
              JOptionPane.showConfirmDialog(null,"Ya estas registrado " );
            }else{
                Jugador.InsertarJugador(txtJugador1.getText());//Inserta los datos de los jugadores
                txtJugador1.enable(false);
            }
       }
    }//GEN-LAST:event_txtJugador1FocusLost

            
    private void txtJugador2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJugador2FocusLost
     if(txtJugador2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debe de llenar correctamente los datos de jugador 2");
       }else{          
            if(Jugador.BuscarNombre(txtJugador2.getText())>0){
              JOptionPane.showConfirmDialog(null,"Ya estas registrado " );
            }else{
                Jugador.InsertarJugador(txtJugador2.getText());//Inserta los datos de los jugadores
                txtJugador2.enable(false);
            }
       }
    }//GEN-LAST:event_txtJugador2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos().setVisible(true);
            }
        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox cmbRegis1;
    private javax.swing.JComboBox cmbRegis2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLbVS;
    private javax.swing.JRadioButton rboJ1Nuevo;
    private javax.swing.JRadioButton rboJ1Regis;
    private javax.swing.JRadioButton rboJ2Nuevo;
    private javax.swing.JRadioButton rboJ2Regis;
    public static java.awt.TextField txtJugador1;
    public static java.awt.TextField txtJugador2;
    // End of variables declaration//GEN-END:variables

}

