
package juego_gato;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Hellen Lopez A-Alejandro Salas
 */
public class Datos extends javax.swing.JFrame {

    
   
    /**
     * Creates new form Datos
     */
    public Datos() {
        initComponents();
        this.getContentPane().setBackground(Color.black);//Hace de color negro el fondo
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJugador2 = new java.awt.TextField();
        jLbVS = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtJugador1 = new java.awt.TextField();
        btnSiguiente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        cmbRegis2 = new javax.swing.JComboBox();
        cmbRegis1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(410, 335));
        getContentPane().setLayout(null);

        txtJugador2.setBackground(new java.awt.Color(0, 0, 0));
        txtJugador2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtJugador2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtJugador2);
        txtJugador2.setBounds(490, 250, 142, 28);

        jLbVS.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLbVS.setForeground(new java.awt.Color(255, 255, 255));
        jLbVS.setText("VS");
        getContentPane().add(jLbVS);
        jLbVS.setBounds(250, 70, 70, 58);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jugador 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 170, 79, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jugador 2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 170, 79, 22);

        txtJugador1.setBackground(new java.awt.Color(0, 0, 0));
        txtJugador1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtJugador1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtJugador1);
        txtJugador1.setBounds(150, 250, 135, 28);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente);
        btnSiguiente.setBounds(170, 310, 90, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(410, 40, 98, 0);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 40, 98, 0);

        Cancelar.setText("Cancelar");
        Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarMouseClicked(evt);
            }
        });
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar);
        Cancelar.setBounds(380, 300, 90, 30);

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Jugador Registrado");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(20, 210, 120, 23);

        jRadioButton2.setText("Nuevo jugador");
        jRadioButton2.setToolTipText("");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(20, 250, 120, 23);

        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Jugador Registrado");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(360, 210, 120, 23);

        jRadioButton4.setText("Nuevo jugador");
        jRadioButton4.setToolTipText("");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(360, 250, 120, 23);

        cmbRegis2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbRegis2);
        cmbRegis2.setBounds(490, 210, 140, 20);

        cmbRegis1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbRegis1);
        cmbRegis1.setBounds(150, 210, 130, 20);
        cmbRegis1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        gato gato = new gato();
        if((txtJugador1.getText().isEmpty())||(txtJugador2.getText().isEmpty())){
            JOptionPane.showMessageDialog(null, "Por favor ingrese los datos que se le solicitan");
        }else{
//            if(gato.BuscarNombre(txtJugador1.getText())> 0){
//                JOptionPane.showMessageDialog(null, "ya existe");
//             }else{
                gato.Insertar(txtJugador1.getText(), txtJugador2.getText());//Inserta los datos de los jugadores
                JOptionPane.showMessageDialog(null, "se guardaron los datos");
                new Rifaa().setVisible(true);// hace el panel de rifa visible
                this.setVisible(false);
//            }
        }        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked

    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarMouseClicked

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        new Menu_Principal().setVisible(true);// hace el el menuprincipal visible
        this.setVisible(false);
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos().setVisible(true);
            }
        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox cmbRegis1;
    private javax.swing.JComboBox cmbRegis2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLbVS;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    public static java.awt.TextField txtJugador1;
    public static java.awt.TextField txtJugador2;
    // End of variables declaration//GEN-END:variables

}

